import {
  Accessibility,
  Activity,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpNarrowWide,
  Award,
  Bell,
  Bookmark,
  Bot,
  CalendarCheck,
  CalendarDays,
  Check,
  CheckCircle2,
  Circle,
  CircleAlert,
  Clock,
  Droplets,
  Dumbbell,
  FileText,
  FlaskConical,
  Flame,
  Footprints,
  Gauge,
  GripVertical,
  History,
  LayoutDashboard,
  List,
  ListPlus,
  MoreVertical,
  PersonStanding,
  Play,
  Plus,
  PlusCircle,
  Printer,
  Moon,
  Scale,
  ScanSearch,
  Search,
  Send,
  Share2,
  Snowflake,
  StickyNote,
  Timer,
  TimerReset,
  TrendingUp,
  Trophy,
  Upload,
  Utensils,
  Video,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  accessibility_new: Accessibility,
  add: Plus,
  add_circle: PlusCircle,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  bolt: Zap,
  bookmark: Bookmark,
  calendar_month: CalendarDays,
  check: Check,
  check_circle: CheckCircle2,
  bedtime: Moon,
  close: X,
  directions_run: Footprints,
  done: Check,
  downhill_skiing: Snowflake,
  drag_indicator: GripVertical,
  emoji_events: Trophy,
  error: CircleAlert,
  event_available: CalendarCheck,
  fitness_center: Dumbbell,
  history: History,
  insights: Activity,
  local_fire_department: Flame,
  manage_search: ScanSearch,
  monitor_weight: Scale,
  more_vert: MoreVertical,
  notifications: Bell,
  picture_as_pdf: FileText,
  play_arrow: Play,
  print: Printer,
  queue_play_next: ListPlus,
  radio_button_unchecked: Circle,
  restaurant: Utensils,
  schedule: Clock,
  science: FlaskConical,
  search: Search,
  send: Send,
  share: Share2,
  skateboarding: PersonStanding,
  smart_toy: Bot,
  snooze: TimerReset,
  speed: Gauge,
  sticky_note_2: StickyNote,
  swap_vert: ArrowUpNarrowWide,
  timelapse: Timer,
  timer: Timer,
  trending_up: TrendingUp,
  trophy: Trophy,
  upload: Upload,
  vertical_align_top: ArrowUp,
  videocam: Video,
  water_drop: Droplets,
  whatshot: Flame,
  workspace_premium: Award,
  space_dashboard: LayoutDashboard,
  format_list_bulleted: List,
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}

export function Icon({ name, size = 20, className, style }: IconProps) {
  const Glyph = ICON_MAP[name] ?? Circle;
  return <Glyph aria-hidden="true" className={className} size={size} style={style} />;
}